== Coding standards

Use the following scripts to check if the code follows  https://www.python.org/dev/peps/pep-0008/[PEP8] and  https://www.python.org/dev/peps/pep-0257/[PEP257] coding standards. These scripts can be run without any arguments:

* `./run-linter.sh` : Use this script to check the indentation, line lengths, variable names, and white space around the operators.

* `./check-docstyle.sh`:  Use this script to check all documentation strings, their presence, and format.

Ensure that you fix any warnings and errors reported by these scripts.

=== Code complexity measurement
Use the following scripts to measure code complexity. These scripts can be run w/o any arguments:

* `./measure-cyclomatic-complexity.sh`: Use this script to measure the  cyclomatic complexity of all the Python sources found in the repository. See this table for further explanation on interpreting the results.
* `./measure-maintainability-index.sh`:  Use this script to measure the maintainability index of all the Python sources found in the repository. See the explanation of this measurement for more details.

=== Dead code detection

The script `detect-dead-code.sh` can be used to detect dead code in the repository. This script can be run w/o any arguments:

----
./detect-dead-code.sh
----

Please note that due to Python's dynamic nature, static code analyzers are likely to miss some dead code. Also, code that is only called implicitly may be reported as unused.

Because of this potential problems, only code detected with more than 90% of confidence is reported.

=== Common issues detection

The script `detect-common-errors.sh` can be used to detect common errors in the repository. This script can be run w/o any arguments:

----
./detect-common-errors.sh
----

Please note that only semantical problems are reported.
